### ISSUE TITLE
10.10 - Yosemite

### ISSUE THREAD

**Issue by jonasschnelli** [x43x61x69/OTX#2]
Just tried to output the txt file on OSX 10.10.3.
But always getting "Error processing File".

**Comment by x43x61x69** [comment]
Hi @jonasschnelli!

I'm sorry but since Apple started their public beta seeding, there'll be too many sub versions of pre-released OS X, and non of which is stable, thus I'll not consider fixing this issue until final version of 10.10.3 is out.

However, since this is an open source project, you could simply modified the code to suit your needs.

Best,
Cai
